# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [33]:
s = "Hi there Sam!"
f=s.split()
print(f)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [4]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [11]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [27]:
abcd=np.zeros(10)
print(abcd)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [36]:
abc=np.ones(10)*5
print(abc)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [35]:
a=np.arange(20,36,2)
print(a)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [29]:
import numpy as np
y=np.arange(0,9).reshape(3,3)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
d=np.concatenate((a,b),axis=0)
print(d)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [21]:
import pandas as pd


In [22]:
import numpy as np
b= np.random.randint(8, size=(3,2))
df = pd.DataFrame(b)
print(df)

   0  1
0  2  7
1  0  3
2  5  7


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [31]:
x=pd.date_range(start='1-1-2023',end='18-1-2023')
print(x)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18'],
              dtype='datetime64[ns]', freq='D')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [24]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [32]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
c=pd.DataFrame(lists)
print(c)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
